# Generated by Django 3.0.7 on 2021-09-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20210910_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lname',
        ),
        migrations.AddField(
            model_name='account',
            name='addres',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='addres',
        ),
    ]
