# Generated by Django 3.0.7 on 2021-09-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_email_token_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrf',
            name='name',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
